version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static  
    ports:
      - "8003:80"
    depends_on:
      - web
